name = "ModelAnalysis"
uuid = "46d4c6b1-fa4b-49bf-9a1f-94c6bce1a78c"
version = "0.1.0"
authors = ["Alexander Robinson <alexander.robinson@awi.de>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SkipNan = "aed68c70-c8b0-4309-8cd1-d392a74f991a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[compat]
DSP = "0.8.4"
DimensionalData = "0.29.24"
ImageFiltering = "0.7.12"
Interpolations = "0.15.1"
Printf = "1.11.0"
YAXArrays = ">=0.7.0"
